feat(postgres): pgdump set n backups to keep

diff --git a/kubernetes/apps/databases/postgres/app/helmrelease.yaml b/kubernetes/apps/databases/postgres/app/helmrelease.yaml
--- a/kubernetes/apps/databases/postgres/app/helmrelease.yaml
+++ b/kubernetes/apps/databases/postgres/app/helmrelease.yaml
@@ -1,4 +1,5 @@
 ---
+# yaml-language-server: $schema=https://raw.githubusercontent.com/bitnami/charts/275b8af69ff830bd5cb6e02ad4d3839dfaa6c234/bitnami/postgresql/values.schema.json
 apiVersion: helm.toolkit.fluxcd.io/v2
 kind: HelmRelease
 metadata:
@@ -47,6 +48,34 @@ spec:
         enabled: true
     backup:
       enabled: true
+      command:
+        - /bin/sh
+        - -c
+        - |
+          BACKUP_DIR=${PGDUMP_DIR}
+          BACKUPS_TO_KEEP=7
+
+          echo "Current backups in ${BACKUP_DIR}:"
+          ls -lh ${BACKUP_DIR}/pg_dumpall-*.pgdump
+
+          pg_dumpall --clean --if-exists --load-via-partition-root --quote-all-identifiers --no-password --file=${BACKUP_DIR}/pg_dumpall-$(date '+%Y-%m-%d-%H-%M').pgdump
+
+          if [ $? -eq 0 ]; then
+            echo "Backup created successfully."
+
+            BACKUPS_TO_DELETE=$(ls -1t $BACKUP_DIR/pg_dumpall-*.pgdump | tail -n +$((BACKUPS_TO_KEEP+1)))
+
+            if [ -n "$BACKUPS_TO_DELETE" ]; then
+              echo "Deleting old backups:"
+              echo "$BACKUPS_TO_DELETE"
+
+              echo "$BACKUPS_TO_DELETE" | xargs -I {} rm -- {}
+            else
+              echo "No backups to delete."
+            fi
+          else
+            echo "Backup creation failed. Old backups will not be deleted."
+          fi
       cronjob:
         storage:
           storageClass: longhorn
